name: Build & FTP Upload Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FTP_LOCATION: ${{ secrets.FTP_LOCATION }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 2
    - uses: ruby/setup-ruby@v1.89.0
      with:
        ruby-version: '3.0.3'
    # Install the gems in the gemfile & install ncftp
    - name: Setup Environment
      run: |
        bundle install
    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build
    # Publish the site
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ env.FTP_LOCATION }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./_site/
        server-dir: public_html/
        dry-run: true
        log-level: verbose