name: Build & Upload Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    # Install the gems in the gemfile & install ncftp
    - name: Setup Environment.
      run: |
        bundle install

    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build
    
    # Push to Github Pages
    - name: Github Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        # Build directory to deploy
        build_dir: _site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_LINK }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: _site/
        server-dir: public_html/
        dry-run: true 
    